### ISSUE TITLE
Report on radar

### ISSUE THREAD

**Issue by lucassbroto** [Kandidatarbete-Chalmers-MCCX02-19-06/RaspberryPiRadarProgram#2]
Hello,

I am Lucas, a Brasilian student in Germany, and I am doing the same thing for my master project. Using an acconeer Radar to figure heart rate and Breathing rate. 

I've taken a look into your codes and they seem a bit complicated and high level, is there a report where you explain the signal processing steps? or a report about the project itself? I would love to read it and try to understand it a bit better.

Thank you so much!
Lucas Broto.

**Comment by danielle123abc** [comment]
Hi Lucas,

Can you already connect the app to the Raspberry?
I have some trouble with loading the MainProgram files:
- python data_acquisition_module.py
- python main.py

I get the error: ModuleNotFoundError: No module named 'acconeer_utils'
The Acconeer Exploration works fine.

Thanks for your response!
Daniëlle Steenge

**Comment by lucassbroto** [comment]
Hey,

So I worked with a different radar, so mine was directly connected to the
computer, no raspberry.

I'm have no clue why that can be your case, but first thing that comes to
mind is the simplest case, path problems with the library.

Have you had access to any report regarding this application?

Best regards,
Lucas.

danielle123abc <notifications@github.com> schrieb am Fr., 22. Mai 2020,
16:25:

**Comment by danielle123abc** [comment]
Hi Lucas,

No, unfortunately it is not due to path problems with the library.

Also I have not been able to find documentation ... I am in contact with Acconeer if they know more about this. I can keep you informed about this?

Greetings,
Danielle

**Comment by lucassbroto** [comment]
Yes please.

I would very much like that.

Thank you so much and good luck.
Lucas.

danielle123abc <notifications@github.com> schrieb am Mo., 25. Mai 2020,
09:29:

**Comment by danielle123abc** [comment]
Hi Lucas,

I just received a response from Acconeer but they only have documentation about the respiration detection and nothing else about the ResPiRadar.
Do you also have an interest in that? Then I could send the PDF files to you.

If I find anything else I'll let you know!
Daniëlle

**Comment by Warnicke** [comment]
Hi! 

Sorry for late answer, but I’m not actively working on the project, so I didn’t see the issue until today. The project was a part of Bachelor's thesis project and the report was therefor obliged to be written in Swedish. I will attach the report [Kandidatarbete-Chalmers-MCCX02-19-06.pdf](https://github.com/Kandidatarbete-Chalmers-MCCX02-19-06/RaspberryPiRadarProgram/files/4678250/Kandidatarbete-Chalmers-MCCX02-19-06.pdf), but you will have to translate it somehow to find it useful. I can give you an overview what the code does. 

The data_acquisition_module.py finds and track peaks in the received signal. Often the peaks with highest amplitude are reflections from the chest, but as there are a lot of nose this can vary so the function tries to follow the closest peak unless a new much higher peak has appeared somewhere else. The change of the phase of the peak gives a relative distance from which movements of the chest can be followed. The movements is then sent to the filter.py to be filtered as there are a lot of noise in the data (especially body movements not connected to the respiratory and heart rate). Different bandpass filters are used for the breath and heart rate. 

The filtered data is then sent to signal_processing_module.py. A Schmitt trigger is used to find the breaths. The output from the Schmitt trigger will be like a pulse function for each breath, and the respiratory rate can be calculated from the lenght of the pulses. To find the heart rate, an FFT was used. Data from the last 20 seconds was used in the FFT. The peaks from the FFT are then found and weighted by their amplitude and distance form the last detected heart rate. The best peak is then supposed to be the heart rate, but usually there are other peaks in the spectrum that are almost as good as the best one. Therefor we also have included some code that compares the differences in amplitude to the other peaks and from that gives the current heart rate some kind of reliability which can be seen in the app by the color of the heart. 

I hope that helped to some extent. Feel free to ask if you have more specific questions. 

Sincerely,
Albin Warnicke

**Comment by danielle123abc** [comment]
Hi Albin,

**Comment by danielle123abc** [comment]
Hi Albin,

Thank you very much for your response!
I have been able to install acconeer_utils but the installation does not proceed to the clients folder.
This is all I got from python setup.py install --user: 
`running install
running bdist_egg
running egg_info
creating lib\acconeer_utils.egg-info
writing lib\acconeer_utils.egg-info\PKG-INFO
writing dependency_links to lib\acconeer_utils.egg-info\dependency_links.txt
writing top-level names to lib\acconeer_utils.egg-info\top_level.txt
writing manifest file 'lib\acconeer_utils.egg-info\SOURCES.txt'
reading manifest file 'lib\acconeer_utils.egg-info\SOURCES.txt'
writing manifest file 'lib\acconeer_utils.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build
creating build\lib
creating build\lib\acconeer_utils
copying lib\acconeer_utils\example_utils.py -> build\lib\acconeer_utils
copying lib\acconeer_utils\mpl_process.py -> build\lib\acconeer_utils
copying lib\acconeer_utils\pg_process.py -> build\lib\acconeer_utils
copying lib\acconeer_utils\__init__.py -> build\lib\acconeer_utils
creating build\bdist.win-amd64
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\acconeer_utils
copying build\lib\acconeer_utils\example_utils.py -> build\bdist.win-amd64\egg\acconeer_utils
copying build\lib\acconeer_utils\mpl_process.py -> build\bdist.win-amd64\egg\acconeer_utils
copying build\lib\acconeer_utils\pg_process.py -> build\bdist.win-amd64\egg\acconeer_utils
copying build\lib\acconeer_utils\__init__.py -> build\bdist.win-amd64\egg\acconeer_utils
byte-compiling build\bdist.win-amd64\egg\acconeer_utils\example_utils.py to example_utils.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\acconeer_utils\mpl_process.py to mpl_process.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\acconeer_utils\pg_process.py to pg_process.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\acconeer_utils\__init__.py to __init__.cpython-37.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying lib\acconeer_utils.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying lib\acconeer_utils.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying lib\acconeer_utils.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying lib\acconeer_utils.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying lib\acconeer_utils.egg-info\zip-safe -> build\bdist.win-amd64\egg\EGG-INFO
creating dist
creating 'dist\acconeer_utils-2.1.1-py3.7.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing acconeer_utils-2.1.1-py3.7.egg`

Do you know how I can fix this?

Best regards,
Danielle

**Comment by danielle123abc** [comment]
`    from acconeer_utils.clients.reg.client import RegClient
ModuleNotFoundError: No module named 'acconeer_utils.clients'`

Is the error I get

**Comment by Warnicke** [comment]
When you use setup.py I think it get data from Acconeers newer version of Exploration Tool, which is completely remade and not supported in this project. The acconeer_utils.clients folder is already inside the copy of Acconeers old version of Exploration Tool in this project, which is the one you should use. I know it can be confusing with the different versions of the Exploration Tool, but in this project it’s just a copied third party source that is already included in the project.

**Comment by danielle123abc** [comment]
How do I install the older version on my local computer? I have already downloaded the older version but when I install it via the setup.py it does automatically go to https://github.com/acconeer/acconeer-python-exploration.

**Comment by Warnicke** [comment]
I think most of the things you need is already installed if you download this project. The only thing missing is the EVK file from Acconeer. Unless you already have installed this, you can download it from https://developer.acconeer.com/ (you have to make an account to download the files).

**Comment by danielle123abc** [comment]
Yes I have also downloaded the EVK file from Acconeer, but when I try to install the supplied Acconeer utilities module from your project it doensn't install the client folder? Is there another way to install the folder without using the setup.py?

This is what I get when I try to install the supplied Acconeer utilities module:

`C:\Users\danielle\acconeer\RaspberryPiRadarProgram-master\acconeer-python-exploration-master>python setup.py install --user
running install
running bdist_egg
running egg_info
creating lib\acconeer_utils.egg-info
writing lib\acconeer_utils.egg-info\PKG-INFO
writing dependency_links to lib\acconeer_utils.egg-info\dependency_links.txt
writing top-level names to lib\acconeer_utils.egg-info\top_level.txt
writing manifest file 'lib\acconeer_utils.egg-info\SOURCES.txt'
reading manifest file 'lib\acconeer_utils.egg-info\SOURCES.txt'
writing manifest file 'lib\acconeer_utils.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build
creating build\lib
creating build\lib\acconeer_utils
copying lib\acconeer_utils\example_utils.py -> build\lib\acconeer_utils
copying lib\acconeer_utils\mpl_process.py -> build\lib\acconeer_utils
copying lib\acconeer_utils\pg_process.py -> build\lib\acconeer_utils
copying lib\acconeer_utils\__init__.py -> build\lib\acconeer_utils
creating build\bdist.win-amd64
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\acconeer_utils
copying build\lib\acconeer_utils\example_utils.py -> build\bdist.win-amd64\egg\acconeer_utils
copying build\lib\acconeer_utils\mpl_process.py -> build\bdist.win-amd64\egg\acconeer_utils
copying build\lib\acconeer_utils\pg_process.py -> build\bdist.win-amd64\egg\acconeer_utils
copying build\lib\acconeer_utils\__init__.py -> build\bdist.win-amd64\egg\acconeer_utils
byte-compiling build\bdist.win-amd64\egg\acconeer_utils\example_utils.py to example_utils.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\acconeer_utils\mpl_process.py to mpl_process.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\acconeer_utils\pg_process.py to pg_process.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\acconeer_utils\__init__.py to __init__.cpython-37.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying lib\acconeer_utils.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying lib\acconeer_utils.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying lib\acconeer_utils.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying lib\acconeer_utils.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying lib\acconeer_utils.egg-info\zip-safe -> build\bdist.win-amd64\egg\EGG-INFO
creating dist
creating 'dist\acconeer_utils-2.1.1-py3.7.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing acconeer_utils-2.1.1-py3.7.egg
Removing c:\users\danielle\appdata\roaming\python\python37\site-packages\acconeer_utils-2.1.1-py3.7.egg
Copying acconeer_utils-2.1.1-py3.7.egg to c:\users\danielle\appdata\roaming\python\python37\site-packages
acconeer-utils 2.1.1 is already the active version in easy-install.pth

Installed c:\users\danielle\appdata\roaming\python\python37\site-packages\acconeer_utils-2.1.1-py3.7.egg
Processing dependencies for acconeer-utils==2.1.1
Finished processing dependencies for acconeer-utils==2.1.1
`

**Comment by Warnicke** [comment]
But do you really need to run setup.py? Is it not working without it?

**Comment by danielle123abc** [comment]
I think so because when I try to run something I get this error:

`Traceback (most recent call last):
  File "examples/basic.py", line 1, in <module>
    from acconeer_utils.clients.reg.client import RegClient
ModuleNotFoundError: No module named 'acconeer_utils.clients'`

**Comment by Warnicke** [comment]
But look in your source code, you should have the folders and path: RaspberryPiRadarProgram/acconeer-python-exploration-master/lib/acconeer_utils/clients/. If it's missing, just download: acconeer_utils/clients/ again from this project.

**Comment by danielle123abc** [comment]
I downloaded the files again but still couldn't install the client module. Then I copied the client folder into the build folder so it installed the client folder but I still have the same error. It's all a bit confusing haha

**Comment by danielle123abc** [comment]
C:\Users\danielle\acconeer\RaspberryPiRadarProgram-master\acconeer-python-exploration-master>python setup.py install --user
running install
running bdist_egg
running egg_info
writing lib\acconeer_utils.egg-info\PKG-INFO
writing dependency_links to lib\acconeer_utils.egg-info\dependency_links.txt
writing top-level names to lib\acconeer_utils.egg-info\top_level.txt
reading manifest file 'lib\acconeer_utils.egg-info\SOURCES.txt'
writing manifest file 'lib\acconeer_utils.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\acconeer_utils
creating build\bdist.win-amd64\egg\acconeer_utils\clients
copying build\lib\acconeer_utils\clients\base.py -> build\bdist.win-amd64\egg\acconeer_utils\clients
copying build\lib\acconeer_utils\clients\configs.py -> build\bdist.win-amd64\egg\acconeer_utils\clients
creating build\bdist.win-amd64\egg\acconeer_utils\clients\json
copying build\lib\acconeer_utils\clients\json\client.py -> build\bdist.win-amd64\egg\acconeer_utils\clients\json
copying build\lib\acconeer_utils\clients\json\protocol.py -> build\bdist.win-amd64\egg\acconeer_utils\clients\json
copying build\lib\acconeer_utils\clients\json\__init__.py -> build\bdist.win-amd64\egg\acconeer_utils\clients\json
copying build\lib\acconeer_utils\clients\links.py -> build\bdist.win-amd64\egg\acconeer_utils\clients
creating build\bdist.win-amd64\egg\acconeer_utils\clients\reg
copying build\lib\acconeer_utils\clients\reg\client.py -> build\bdist.win-amd64\egg\acconeer_utils\clients\reg
copying build\lib\acconeer_utils\clients\reg\protocol.py -> build\bdist.win-amd64\egg\acconeer_utils\clients\reg
copying build\lib\acconeer_utils\clients\reg\utils.py -> build\bdist.win-amd64\egg\acconeer_utils\clients\reg
copying build\lib\acconeer_utils\clients\reg\__init__.py -> build\bdist.win-amd64\egg\acconeer_utils\clients\reg
copying build\lib\acconeer_utils\example_utils.py -> build\bdist.win-amd64\egg\acconeer_utils
copying build\lib\acconeer_utils\mpl_process.py -> build\bdist.win-amd64\egg\acconeer_utils
copying build\lib\acconeer_utils\pg_process.py -> build\bdist.win-amd64\egg\acconeer_utils
copying build\lib\acconeer_utils\__init__.py -> build\bdist.win-amd64\egg\acconeer_utils
byte-compiling build\bdist.win-amd64\egg\acconeer_utils\clients\base.py to base.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\acconeer_utils\clients\configs.py to configs.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\acconeer_utils\clients\json\client.py to client.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\acconeer_utils\clients\json\protocol.py to protocol.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\acconeer_utils\clients\json\__init__.py to __init__.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\acconeer_utils\clients\links.py to links.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\acconeer_utils\clients\reg\client.py to client.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\acconeer_utils\clients\reg\protocol.py to protocol.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\acconeer_utils\clients\reg\utils.py to utils.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\acconeer_utils\clients\reg\__init__.py to __init__.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\acconeer_utils\example_utils.py to example_utils.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\acconeer_utils\mpl_process.py to mpl_process.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\acconeer_utils\pg_process.py to pg_process.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\acconeer_utils\__init__.py to __init__.cpython-37.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying lib\acconeer_utils.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying lib\acconeer_utils.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying lib\acconeer_utils.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying lib\acconeer_utils.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying lib\acconeer_utils.egg-info\zip-safe -> build\bdist.win-amd64\egg\EGG-INFO
creating 'dist\acconeer_utils-2.1.1-py3.7.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing acconeer_utils-2.1.1-py3.7.egg
Removing c:\users\danielle\appdata\roaming\python\python37\site-packages\acconeer_utils-2.1.1-py3.7.egg
Copying acconeer_utils-2.1.1-py3.7.egg to c:\users\danielle\appdata\roaming\python\python37\site-packages
acconeer-utils 2.1.1 is already the active version in easy-install.pth

Installed c:\users\danielle\appdata\roaming\python\python37\site-packages\acconeer_utils-2.1.1-py3.7.egg
Processing dependencies for acconeer-utils==2.1.1
Finished processing dependencies for acconeer-utils==2.1.1

C:\Users\danielle\acconeer\RaspberryPiRadarProgram-master\acconeer-python-exploration-master>python examples/basic.py -s 192.168.178.22
Traceback (most recent call last):
  File "examples/basic.py", line 1, in <module>
    from acconeer_utils.clients.reg.client import RegClient
ModuleNotFoundError: No module named 'acconeer_utils.clients'

**Comment by Warnicke** [comment]
When we used the project, we used it directly on the Rasberry Pi. But perhaps it will work on a PC too. But I don't still get it why you need to run setyp.py? What happens if you download and run the program whithout first running setup.py?

**Comment by danielle123abc** [comment]
In order for your data_acquisition_module.py and main.py to run, you need different imports from Acconeer. These imports are installed on my local machine when setup.py is running.

The import in main.py:
import data_acquisition_module # Import class which collects and filters relevant data from radar

The imports in data_acquisition_module:
# Imports from Acconeer for radar data acquisition
from acconeer_utils.clients.reg.client import RegClient
from acconeer_utils.clients.json.client import JSONClient
from acconeer_utils.clients import configs
from acconeer_utils import example_utils
from acconeer_utils.pg_process import PGProcess, PGProccessDiedException

Because the acconeer_utils.clients is not installed, the code crashes here. So without running the setup.py first, it doesn't work either because the code still needs the acconeer_utils.clients. Hope it is something clearer?

**Comment by danielle123abc** [comment]
In order for your data_acquisition_module.py and main.py to run, you need different imports from Acconeer. These imports are installed on my local machine when setup.py is running.

The import in main.py:
import data_acquisition_module # Import class which collects and filters relevant data from radar

The imports in data_acquisition_module:
# Imports from Acconeer for radar data acquisition
from acconeer_utils.clients.reg.client import RegClient
from acconeer_utils.clients.json.client import JSONClient
from acconeer_utils.clients import configs
from acconeer_utils import example_utils
from acconeer_utils.pg_process import PGProcess, PGProccessDiedException

Because the acconeer_utils.clients is not installed, the code crashes here. So without running the setup.py first, it doesn't work either because the code still needs the acconeer_utils.clients. Hope it is something clearer?

**Comment by danielle123abc** [comment]
In order for your data_acquisition_module.py and main.py to run, you need different imports from Acconeer. These imports are installed on my local machine when setup.py is running.

The import in main.py:
import data_acquisition_module # Import class which collects and filters relevant data from radar

The imports in data_acquisition_module:
#Imports from Acconeer for radar data acquisition
from acconeer_utils.clients.reg.client import RegClient
from acconeer_utils.clients.json.client import JSONClient
from acconeer_utils.clients import configs
from acconeer_utils import example_utils
from acconeer_utils.pg_process import PGProcess, PGProccessDiedException

Because the acconeer_utils.clients is not installed, the code crashes here. So without running the setup.py first, it doesn't work either because the code still needs the acconeer_utils.clients. Hope it is something clearer?

**Comment by Warnicke** [comment]
But all of the files in:

from acconeer_utils.clients.reg.client import RegClient
from acconeer_utils.clients.json.client import JSONClient
from acconeer_utils.clients import configs
from acconeer_utils import example_utils
from acconeer_utils.pg_process import PGProcess, PGProccessDiedException

are already in this project at: RaspberryPiRadarProgram/acconeer-python-exploration-master/lib/acconeer_utils/. So you shouldn't need to run the setup.py because Python is supposed to run the local files instead of the files setyp.py is creating.

**Comment by Warnicke** [comment]
You probably have to remove the package installed at: c:\users\danielle\appdata\roaming\python\python37\site-packages\acconeer_utils-2.1.1-py3.7.egg for it to work.

**Comment by danielle123abc** [comment]
I reinstalled it again without running setup.py and removed c: \ users \ danielle \ appdata \ roaming \ python \ python37 \ site-packages \ acconeer_utils-2.1.1-py3.7.egg but I still get always the same error ... I also added the path but now I get the error that he can't even find acconeer_utils ..
     from acconeer_utils.clients.reg.client import RegClient
ModuleNotFoundError: No module named 'acconeer_utils'

**Comment by Warnicke** [comment]
I'm not an expert on Python, but can it help by copying the whole Exploration Tool to c:\users\\[User name]\appdata\roaming\python\python37\site-packages? Otherwise you have to find a way to import the moduls locally. Perhaps will it be easier to copy the files in MainProgram to the Exploration Tools folder?

**Comment by danielle123abc** [comment]
Yesss it worked! I moved the entire Exploration Tool to c: \ users \ danielle \ appdata \ roaming \ python \ python37 \ site packages and created new paths and then it worked. Thank you so much!
